PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX a: <http://www.daml.org/2001/01/gedcom/gedcom#>

SELECT DISTINCT ?royal_marriage_place
WHERE {
	?x a:place ?royal_marriage_place .
	?x rdf:type a:Marriage .
}