PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX a: <http://www.daml.org/2001/01/gedcom/gedcom#>

SELECT DISTINCT ?place_in_The_Netherlands
WHERE {
	?x a:place ?place_in_The_Netherlands .
	?x rdf:type a:Marriage .
	FILTER regex(?place_in_The_Netherlands, "Netherlands")
}