PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX a: <http://www.daml.org/2001/01/gedcom/gedcom#>

SELECT ?z
WHERE {
	?x a:name "Beatrix of_Netherlands //" .

	?x a:spouseIn ?y .
	
	{ ?w a:spouseIn ?y . } UNION { ?w a:childIn ?y . }
	?w a:name ?z .
	FILTER (?z != "Beatrix of_Netherlands //")
}